name: Merge Upstream PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '3 7 * * *'

jobs:
  merge-upstream-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/jkrejcha/AdmiraList.git
          git fetch upstream master

      - name: Get all open PRs from upstream with source repo information
        id: get_prs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PRS=$(gh pr list --repo jkrejcha/AdmiraList --state open --json headRepositoryOwner,headRepository,headRefName,createdAt | jq -c '[.[] | select(.headRepository != null) | {repo: "\(.headRepositoryOwner.login)/\(.headRepository.name)", branch: .headRefName, createdAt: .createdAt}]')
          echo "PRS=${PRS}" | tee -a $GITHUB_ENV

      - name: Merge PR branches into local branch
        run: |
          LOCAL_BRANCH="upstream-prs"
          git checkout -b $LOCAL_BRANCH
          git reset --hard upstream/master

          # Iterate over the JSON array
          echo "$PRS" | jq -c '.[]' | while read -r pr; do
            repo=$(echo "$pr" | jq -r '.repo')
            branch=$(echo "$pr" | jq -r '.branch')
            # Add and fetch the remote if it doesn't already exist
            if ! git remote | grep -q "${repo}"; then
              git remote add "${repo}" "https://github.com/${repo}.git"
            fi
            git fetch "${repo}" "${branch}"

            # Merge the PR branch into the local branch
            if git merge --no-ff "${repo}/${branch}"; then
              echo "Merged ${repo}/${branch}"
            else
              # git merge --abort
              echo "Merge conflict with ${repo}/${branch}, accepting both changes"
              git status | grep 'both modified' | awk '{print $3}' | xargs sed -i -E '/^<<<<<<<|^=======|^>>>>>>>/d'
            fi
          done

          git log upstream/master..HEAD
          # git push origin $LOCAL_BRANCH --force